# Generated by Django 4.1.1 on 2023-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryst',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
